// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: embeddings.sql

package db

import (
	"context"
	"database/sql"
)

const createEmbedding = `-- name: CreateEmbedding :one
INSERT INTO embeddings (
    node_id,
    session_id,
    vector_id,
    vector,
    dims,
    metadata,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, strftime('%s', 'now')
)
RETURNING id, node_id, session_id, vector_id, vector, dims, metadata, created_at
`

type CreateEmbeddingParams struct {
	NodeID    int64          `json:"node_id"`
	SessionID sql.NullString `json:"session_id"`
	VectorID  sql.NullString `json:"vector_id"`
	Vector    []byte         `json:"vector"`
	Dims      sql.NullInt64  `json:"dims"`
	Metadata  interface{}    `json:"metadata"`
}

func (q *Queries) CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) (Embedding, error) {
	row := q.queryRow(ctx, q.createEmbeddingStmt, createEmbedding,
		arg.NodeID,
		arg.SessionID,
		arg.VectorID,
		arg.Vector,
		arg.Dims,
		arg.Metadata,
	)
	var i Embedding
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SessionID,
		&i.VectorID,
		&i.Vector,
		&i.Dims,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmbedding = `-- name: DeleteEmbedding :exec
DELETE FROM embeddings
WHERE id = ?
`

func (q *Queries) DeleteEmbedding(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteEmbeddingStmt, deleteEmbedding, id)
	return err
}

const getEmbeddingByVectorID = `-- name: GetEmbeddingByVectorID :one
SELECT id, node_id, session_id, vector_id, vector, dims, metadata, created_at
FROM embeddings
WHERE vector_id = ?
LIMIT 1
`

func (q *Queries) GetEmbeddingByVectorID(ctx context.Context, vectorID sql.NullString) (Embedding, error) {
	row := q.queryRow(ctx, q.getEmbeddingByVectorIDStmt, getEmbeddingByVectorID, vectorID)
	var i Embedding
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SessionID,
		&i.VectorID,
		&i.Vector,
		&i.Dims,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getEmbeddingsByNode = `-- name: GetEmbeddingsByNode :many
SELECT id, node_id, session_id, vector_id, vector, dims, metadata, created_at
FROM embeddings
WHERE node_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetEmbeddingsByNode(ctx context.Context, nodeID int64) ([]Embedding, error) {
	rows, err := q.query(ctx, q.getEmbeddingsByNodeStmt, getEmbeddingsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Embedding{}
	for rows.Next() {
		var i Embedding
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.SessionID,
			&i.VectorID,
			&i.Vector,
			&i.Dims,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
