// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type AnalysisMetadatum struct {
	ID          int64          `json:"id"`
	NodeID      sql.NullInt64  `json:"node_id"`
	SessionID   sql.NullString `json:"session_id"`
	Tier        int64          `json:"tier"`
	Result      interface{}    `json:"result"`
	Status      sql.NullString `json:"status"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type CodeNode struct {
	ID        int64          `json:"id"`
	SessionID string         `json:"session_id"`
	Path      string         `json:"path"`
	Language  sql.NullString `json:"language"`
	Symbol    sql.NullString `json:"symbol"`
	Kind      sql.NullString `json:"kind"`
	StartLine sql.NullInt64  `json:"start_line"`
	EndLine   sql.NullInt64  `json:"end_line"`
	Metadata  interface{}    `json:"metadata"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Dependency struct {
	ID        int64          `json:"id"`
	FromNode  int64          `json:"from_node"`
	ToNode    int64          `json:"to_node"`
	Relation  sql.NullString `json:"relation"`
	Metadata  interface{}    `json:"metadata"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Embedding struct {
	ID        int64          `json:"id"`
	NodeID    int64          `json:"node_id"`
	SessionID sql.NullString `json:"session_id"`
	VectorID  sql.NullString `json:"vector_id"`
	Vector    []byte         `json:"vector"`
	Dims      sql.NullInt64  `json:"dims"`
	Metadata  interface{}    `json:"metadata"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Message struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Model      sql.NullString `json:"model"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
	Provider   sql.NullString `json:"provider"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
}
