// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAnalysisMetadata(ctx context.Context, arg CreateAnalysisMetadataParams) (AnalysisMetadatum, error)
	CreateCodeNode(ctx context.Context, arg CreateCodeNodeParams) (CodeNode, error)
	CreateDependency(ctx context.Context, arg CreateDependencyParams) (Dependency, error)
	CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) (Embedding, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteCodeNode(ctx context.Context, id int64) error
	DeleteDependency(ctx context.Context, id int64) error
	DeleteEmbedding(ctx context.Context, id int64) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetCodeNode(ctx context.Context, id int64) (CodeNode, error)
	GetEmbeddingByVectorID(ctx context.Context, vectorID sql.NullString) (Embedding, error)
	GetEmbeddingsByNode(ctx context.Context, nodeID int64) ([]Embedding, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	ListAnalysisByNode(ctx context.Context, nodeID sql.NullInt64) ([]AnalysisMetadatum, error)
	ListAnalysisBySession(ctx context.Context, sessionID sql.NullString) ([]AnalysisMetadatum, error)
	ListCodeNodesByPath(ctx context.Context, path string) ([]CodeNode, error)
	ListCodeNodesBySession(ctx context.Context, sessionID string) ([]CodeNode, error)
	ListDependenciesFrom(ctx context.Context, fromNode int64) ([]Dependency, error)
	ListDependenciesTo(ctx context.Context, toNode int64) ([]Dependency, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListSessions(ctx context.Context) ([]Session, error)
	UpdateAnalysisStatus(ctx context.Context, arg UpdateAnalysisStatusParams) (AnalysisMetadatum, error)
	UpdateCodeNode(ctx context.Context, arg UpdateCodeNodeParams) (CodeNode, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
